resolver: nightly-2021-02-12

packages:
  - .

extra-deps:
  - numhask-0.7.1.0
  - numhask-array-0.8.0
  - numhask-free-0.0.3
  - random-1.2.0
  - chart-svg-0.2.2
  - numhask-space-0.7.1.0
  - perf-0.7.0
  - mealy-0.0.3

allow-newer: true
